config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'categories/index' => 'categories_controller#index'
  get 'post/index' => 'posts_controller#index'
  get 'home/index' => 'home_controller#index'
  root 'home#index'
  resources :posts
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  accepts_nested_attributes_for :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to @category, notice: "Category Saved"
    else
      render :new
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  def category_params
    params.require(:category).premit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.create(post_params)

    if @post.save
      redirect_to @post, notice: "Your post has been saved"
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attribute(post_params)
      redirect_to @post, notice: "Your post has been updated"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "Your post has been deleted"
  end

  private
  def post_params
    params.require(:post).permit(:title,:body,:category_id,:author_id, categories_attribute: [:name])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul class="categories">
<% @categories.each do |category| %>
  <li><h3><%= link_to category.name, category %></h3></li>
    <% category.post.each do |post| %>
      <li><h5><%= link_to post.title, post%></h5></li>
    <% end %>
  <hr></hr>
<% end %>
</ul>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<% @category.post.each do |post| %>
<h5> <%= link_to post.title, post %>  </h5>
<% end %>
<%= link_to "Back", :back %>

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default" role='navigation'>
      <div class="container">
        <div class="navbar-header">
          <ul class="nav nav-tabs" role="tablist">
            <li><%= link_to "Home", root_url, class: 'btn btn-primary'%></li>
            <li><%= link_to "Category", categories_path, class: 'btn btn-primary'%></li>
            <li><%= link_to "Posts", posts_path, class: 'btn btn-primary'%></li>
          </ul>
        </div>
      </div>
    </div>
    <% flash.each do |key,value| %>
    <p> <%= value%> </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>

<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/>
</p>

<p>
  <%= f.label :body %><br/>
  <%= f.text_field :body , size: "60x600"%><br/>
</p>

<p>
  <%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}%> <br/>
</p>

<p>
  <%= f.submit "Update Post"%>
  |<%=link_to "Delete Post", @post, method: :delete, data: {confirm: "Are you sure?"} %> | <%= link_to "Go Back", post_path %>
</p>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
<div id="post">
  <h3 class="post-title"><%= link_to post.title, post %></h3>
  <h5 class="post-catgeory"><%= link_to post.category.name, post.category%></h5>
  <p class="post-body"><%= post.body %></p>
</div>
<% end %>
<%= link_to "Add New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for @post do |f| %>

<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/>
</p>

<p>
  <%= f.label :body %><br/>
  <%= f.text_field :body , size: "60x600"%><br/>
</p>

<p>
  <%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}%> <br/>
</p>

<p>
  <%= f.submit "Add Post"%>
</p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %> <h3><%=link_to "Back", posts_path %></h3></h1>
<p><%= @post.body %></p>
<small><%= @post.created_at.strftime("%D") %></small>
<%= link_to "Edit Post", edit_post_path %>